version: '3'
services: 
    manager:
        image: SETUP_APP_NAME:latest
        volumes: 
            - config:/home/node/app/config
            - logs:/home/node/app/logs
        depends_on:
            - redis
        environment: 
            - INSTANCE_GROUP_ID: RANDOM
            - INSTANCE_MODE: MANAGER_EXCLUSIVE
            - NODE_ENV: production
    servers:
        image: SETUP_APP_NAME:latest
        depends_on:
            - redis
        ports:
            - "8000"
        volumes:
            - config:/home/node/app/config
            - logs:/home/node/app/logs
        environment: 
            - INSTANCE_GROUP_ID: RANDOM
            - INSTANCE_MODE: EXTENDED
            - NODE_ENV: production
    redis:
        image: redis:latest
        ports:
            - "SETUP_REDIS_PORT:6379"
    nginx:
        depends_on:
            - servers
        volumes:
            - key.pem:/etc/key.pem:ro
            - cert.pem:/etc/cert.pem:ro
            - nginx.conf:/etc/nginx/nginx.conf:ro